config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/dashboard' => 'dashboard#index'
    resources :users
  end
  get '/dashboard' => 'dashboard#index'
  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  get "/logout" => "sessions#logout", as: :logout



  resources :users do
    member do
      post :changepassword
    end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :hash_password
  validates :name, presence:true
  validates :address, presence:true
  validates :phone, presence: true, uniqueness:true
  validates :email, presence:true, uniqueness:true
  validates :password, presence:true, length: {minimum:6}, confirmation: true
  self.per_page = 3
  def hash_password
    self.password = Digest::MD5::hexdigest(self.password)

  end

  def authenticate(password)
    password_hash = Digest::MD5::hexdigest(password)
    return true if password_hash == self.password
    return false
  end

  def is_admin
    if self.role == 1
      return true
    else
      return false
    end
  end

  def is_user
    if self.role == 0
      return true
    else
      return false
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  def permission


  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index

  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  skip_before_action :authenticate!

  def index
     @users = User.where(role: 0).paginate(:page => params[:page])
  end
  def new
     @user = User.new
  end

  def create
    @user = User.new user_params
    if  @user.save
      flash[:success] = "Thêm mới thành công!"
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
       @user.assign_attributes user_params
     if @user.valid?
       @user.update(user_params)
       flash[:success] = "Chỉnh sửa thành công!"
       redirect_to admin_users_path
    else
       render :edit
    end
  end


    def destroy
       @user = User.find(params[:id])
      if
       @user.destroy
       render json: {success: true}
     end
    end

  private
  def user_params
    params.require(:user).permit(:email, :password, :name, :phone, :address, :role)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  before_action :authenticate!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    @current_user ||= User.find_by id: session[:user_id]

  end

  def authenticate!
    redirect_to login_path if @current_user.nil?

  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  def index

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate!
  def new
    if @current_user
      redirect_to admin_dashboard_path if @current_user.is_admin
      redirect_to dashboard_path if @current_user.is_user
    end
  end
  def create
    user = User.find_by email: params[:session][:email]
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to admin_dashboard_path if user.is_admin
      redirect_to dashboard_path if user.is_user

    else
      flash[:error] = "email or password invalid"
      render :new
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to login_path

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate!, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "create a new user successfuly"
      redirect_to login_path
    else
      render :new
    end
  end

  def edit
      @user= User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
       @user.assign_attributes user_params
     if @user.valid?
       @user.update(user_params)
       flash[:success] = "Chỉnh sửa thành công!"

      redirect_to admin_dashboard_path if @user.is_admin
      redirect_to dashboard_path if @user.is_user
    else
       render :edit
    end
  end

  def changepassword
    @user= User.find(params[:id])
    @user.assign_attributes password_params
    if Digest::MD5::hexdigest(params[:old_password]) == @user.password
      if params[:password] == params[:password_confirmation]
        @user.update(password: params[:password])
        flash[:success] = "Change password successfuly"
      end
    else
      flash[:error_change] = "password is not correct"
    end
    redirect_to edit_user_path

  end


  private

  def user_params
    params.require(:user).permit(:name, :address, :phone, :email, :password)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard/index.html.erb
<%if flash[:success]%>
  <div class="alert alert-success">
    <%=flash[:success]%>
  </div>
<%end%>

<a href="<%= admin_users_path%>" class = "btn btn-info">Quản lý user</a>

app/views/admin/users/edit.html.erb
<% if flash[:error_change] %>
<div class="col-md-12 alert-danger alert">
<%= flash[:error] %>
</div>
<% end %>


  <% if @user.errors.any?%>
    <ul class = "alert alert-danger">
      <% @user.errors.full_messages.each do |message|%>
      <li><%= message%></li>
    </ul>
      <%end%>
  <%end%>
<%= form_for @user, url: admin_user_path(@user) do |f| %>
<div class="col-md-4 col-sm-offset-4">
  <div class="form-group">
    <label for="exampleInputName2">Họ tên</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Họ tên" %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail2">Địa chỉ</label>
    <%= f.text_field :address, class: "form-control", placeholder: "Địa chỉ" %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail2">Số điện thoại</label>
    <%= f.text_field :phone, class: "form-control", placeholder: "Số điện thoại" %>
  </div>
  <div class="form-group">
    <label for="exampleInputName2">Email</label>
    <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>

  <div class="text-center">
    <button type="submit" name="button" class="btn btn-primary ">Sửa</button>
  </div>
  </div>


<% end %>

app/views/admin/users/index.html.erb
<% if flash[:success] %>
  <div >
    <ul class = "alert alert-success ">
      <li> <%= flash[:success]%> </li>
    </ul>

  </div>
<%end%>

<div class="message"></div>

<a href="<%= new_admin_user_path%>" class="btn btn-info">create user</a>

<h3 >Danh sách User</h3>
<div class="list-user">
<table class="table table-hover table-bordered" >
  <tr style="background: pink">
    <th>STT</th>
    <th>Tên </th>
    <th>Địa chỉ</th>
    <th>Số điện thoại</th>
    <th>Email</th>
    <th>Chức năng</th>
  </tr>

  <% @users.each_with_index do |user,index| %>
  <tr class="box-user">
    <td><%= index+1%></td>
    <td><%= user.name %></td>
    <td><%= user.address %></td>
    <td><%= user.phone%></td>
    <td><%= user.email %></td>
    <td>
      <a href="<%= edit_admin_user_path(user) %>" class="btn btn-info">Sửa</a>
      <a data-target=" <%= user.id %>" class="btn btn-danger delete-user" data-confirm="Bạn chắc chắn muốn xóa?">Xóa</a>
    </td>
  </tr>
  <% end %>
</table>
<div class="pull-right "><%= will_paginate @users, :style => 'color:blue' %></div>
</div>

app/views/admin/users/new.html.erb
  <% if @user.errors.any? %>
  <div class="col-md-12 alert-danger alert">
  <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </div>
  <% end %>

<%= form_for @user, url: admin_users_path  do |f| %>
<h1 class="text-center" style="color:#B22222">Register</h1>

<div class="col-md-4 col-sm-offset-4">
  <div class="form-group">
    <label for="exampleInputName2">Họ tên</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Họ tên" %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail2">Địa chỉ</label>
    <%= f.text_field :address, class: "form-control", placeholder: "Địa chỉ" %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail2">Số điện thoại</label>
    <%= f.text_field :phone, class: "form-control", placeholder: "Số điện thoại" %>
  </div>
  <div class="form-group">
    <label for="exampleInputName2">Email</label>
    <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail2">Password</label>
    <%= f.text_field :password, class: "form-control", placeholder: "Mật khẩu" %>
  </div>
  <div class="text-center">
    <button type="submit" name="button" class="btn btn-primary ">Thêm</button>
  </div>
  </div>


<% end %>

app/views/dashboard/index.html.erb
<%if flash[:success]%>
  <ul class="alert alert-success">
    <li><%=flash[:success]%></li>
  </ul>

<%end%>
user

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <% if yield(:meta).blank? %>
<title>Controller stadium</title>
  <% else %>
  <%= yield(:meta) %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <% if @current_user && @current_user.is_admin %>
    <%= render "partils/headeradmin" %>
  <%  end%>
  <% if !@current_user || @current_user.is_user   %>
    <%= render "partils/headeruser" %>
  <% end%>
<%= yield %>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/partils/_headeradmin.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>


      <a class="navbar-brand" href="<%= login_path%>">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><a href="">Actions</a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if @current_user %>
        <li ><a href="<%= edit_user_path(@current_user.id)  %>">  <%= @current_user.name %></a></li>

        <li class="active"><a href="<%= logout_path %>">Logout <span class="sr-only">(current)</span></a></li>
        <% else %>
        <li class="active"><a href="<%= login_path %>">Login <span class="sr-only">(current)</span></a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partils/_headeruser.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>


      <a class="navbar-brand" href="<%= login_path%>">HomeUser</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><a href="">Actions</a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if @current_user %>
        <li ><a href="<%= edit_user_path(@current_user.id)  %>">  <%= @current_user.name %></a></li>

        <li class="active"><a href="<%= logout_path %>">Logout <span class="sr-only">(current)</span></a></li>
        <% else %>
        <li class="active"><a href="<%= login_path %>">Login <span class="sr-only">(current)</span></a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- <html>
<head>


<link href="../assets/style.css" rel="stylesheet" type="text/css" media="all" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<!--slider-->
<!-- <link href="../assets/slider.css" rel="stylesheet" type="text/css" media="all"/>
</head>
<body>
<div class="header">
    <div class="header-top">
        <div class="wrap">
                <div class="logo">
                    <a href="index.html"><img src="../assets/logo.png" alt=""></a>
                </div>
                <div class="search_box">
                <form>
                   <input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}"><input type="submit" value="">
                </form>
            </div>
            <div class="clear"></div>
        </div>
   </div>
    <div class="header-bottom">
         <div class="wrap">
             <div id='cssmenu'>
                <ul class=" navbar-nav">
                   <li class='active'><a href='<%=login_path %>'><span>Home</span></a></li>
          <% if @current_user && @current_user.is_admin %>
         <li><a href="#">Giáo viên</a></li>
                    <li><a href="<%= admin_dashboard_students_path %>">Học viên</a></li>
          <% else %>
         <% if @current_user && @current_user.is_teacher %>
         <li><a href="#">Khoá học</a></li>
         <% else %>
         <li><a href="#">Khoá học</a></li>
                    <li><a href="#">Lớp học đã ĐK</a></li>
         <% end %>
           <% end %>

                </ul>
       <ul class=" navbar-nav navbar-right">
         <% if @current_user %>
         <li><a style="font-weight: bold"><%= @current_user.name %></a></li>
         <li class="last login"><a href="<%= logout_path %>">Logout</a></li>
         <% else %>
         <li class="last login"><a href="<%= login_path %>">Login</a></li>
         <% end %>
       </ul>
       <div class="clear"></div>
              </div>
         </div>
   </div>
</div> --> -->

app/views/users/edit.html.erb
<% if flash[:error_change] %>
<div class="col-md-12 alert-danger alert">
<%= flash[:error_change] %>
</div>
<% end %>


  <% if @user.errors.any?%>
    <ul class = "alert alert-danger">
      <% @user.errors.full_messages.each do |message|%>
      <li><%= message%></li>
        <%end%>
    </ul>

  <%end%>

<div class="col-md-6">
  <%= form_for @user, url: user_path(@user) do |f| %>
  <div class="form-group">
    <label for="exampleInputName2">Họ tên</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Họ tên" %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail2">Địa chỉ</label>
    <%= f.text_field :address, class: "form-control", placeholder: "Địa chỉ" %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail2">Số điện thoại</label>
    <%= f.text_field :phone, class: "form-control", placeholder: "Số điện thoại" %>
  </div>
  <div class="form-group">
    <label for="exampleInputName2">Email</label>
    <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>

  <div class="">
    <button type="submit" name="button" class="btn btn-primary ">Sửa</button>
  </div>
  <%end%>
  </div>



  <div class="col-md-6">
    <form action="<%= changepassword_user_path(@current_user.id) %>" method="post">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <div class="form-group">
        <label for="exampleInputEmail1">Mật khẩu củ</label>
        <input type="password" class="form-control" name="old_password" id="exampleInputEmail1" placeholder="mật khẩu củ">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">mật khẩu mới</label>
        <input type="password" class="form-control" name="user[password]" id="exampleInputPassword1" placeholder="mật khẩu mới">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">xác minh lại</label>
        <input type="password" class="form-control" name="user[password_confirmation]" id="exampleInputPassword1" placeholder="xác minh lại">
      </div>
      <button type="submit" class="btn btn-primary">Thay đổi mật khẩu</button>
    </form>

  </div>

app/views/users/new.html.erb
<%if @user.errors.any? do |error|%>
  <ul class="alert alert-danger">
    <% @user.errors.full_messages.each do |message|  %>
    <li><%= message%></li>
    <%end%>
  </ul>
<%end%>
<%end%>
<div class="col-md-4 col-sm-offset-4">
<%= form_for @user  do |f|%>



  <div class="form-group">
    <lable>Name</lable>
    <%= f.text_field :name, class: "form-control", placeholder: "name"%>
  </div>

  <div class="form-group">
    <lable>Address</lable>
    <%= f.text_field :address, class: "form-control", placeholder: "address"%>
  </div>

  <div class="form-group">
    <lable>Phone</lable>
    <%= f.text_field :phone, class: "form-control", placeholder: "phone"%>
  </div>

  <div class="form-group">
    <lable>Email</lable>
    <%= f.text_field :email, class: "form-control", placeholder: "email "%>
  </div>

  <div class="form-group">
    <lable>password</lable>
    <%= f.text_field :password, class: "form-control", placeholder: "password"%>
  </div>

  <button type="submit" class="btn btn-primary">create</button>
<%end%>
</div>